# Generated by Django 4.1.7 on 2023-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paper_4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paper_5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paper_6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paper_7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pdc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pdc_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_1_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_2_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_3_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_4_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_5_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_6_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_7_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='thesis',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thesis_check',
            field=models.BooleanField(default=False),
        ),
    ]
