# Generated by Django 4.1.7 on 2023-03-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_paper_4_user_paper_5_user_paper_6_user_paper_7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aps',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aps_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_synopsis',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pre_synopsis_check',
            field=models.BooleanField(default=False),
        ),
    ]
