# Generated by Django 4.1.7 on 2023-03-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_aps_user_aps_check_user_cv_user_cv_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aps_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pdc_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pre_synopsis_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_1_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_2_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_3_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_4_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_5_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_6_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_7_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thesis_check',
            field=models.TextField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
    ]
