# Generated by Django 4.1.7 on 2023-03-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_aps_check_alter_user_cv_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(choices=[('not specified', 'not specified'), ('male', 'male'), ('female', 'female')], default='not specified'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='research_area',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='aps_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pdc_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pre_synopsis_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_1_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_2_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_3_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_4_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_5_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_6_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_7_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thesis_check',
            field=models.TextField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending'),
        ),
    ]
