# Generated by Django 4.1.7 on 2023-03-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_address_user_father_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/2/2c/Default_pfp.svg', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=60),
        ),
    ]
