# Generated by Django 4.1.7 on 2023-04-04 08:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='json',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
