# Generated by Django 4.1.7 on 2023-04-11 03:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_json_user_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conference',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='patent',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
