# Generated by Django 4.1.7 on 2023-04-11 04:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_conference_user_patent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conference',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='patent',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='publications',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
