# Generated by Django 4.1.7 on 2023-04-11 04:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_conference_alter_user_patent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='conference',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='patent',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='publications',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
